// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKEFG6bwV3zifFe1s7TL804VgMgV4Dgds',
    appId: '1:200725392213:web:da12df441ae90b31ad1ddc',
    messagingSenderId: '200725392213',
    projectId: 'bootcamp-tutorail',
    authDomain: 'bootcamp-tutorail.firebaseapp.com',
    storageBucket: 'bootcamp-tutorail.appspot.com',
    measurementId: 'G-FBVWWXHSPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc6ye_QA30aEtAeXRqvABxb02ZCuxQQA0',
    appId: '1:200725392213:android:e499985d07266296ad1ddc',
    messagingSenderId: '200725392213',
    projectId: 'bootcamp-tutorail',
    storageBucket: 'bootcamp-tutorail.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDswjkSuj2tf_mvAuTMUd05gorw0XO1xaY',
    appId: '1:200725392213:ios:da64384cceb23bd4ad1ddc',
    messagingSenderId: '200725392213',
    projectId: 'bootcamp-tutorail',
    storageBucket: 'bootcamp-tutorail.appspot.com',
    iosClientId: '200725392213-9kkdckmtk4qpg4pii1hqqdnih809dsoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );
}
